# os:
#   - Visual Studio 2019
# platform:
#   - x64

# Build worker image (VM template)
# image: Visual Studio 2015


environment:
  global:
    # git repo from which to pull orange3 sources
    REPO: https://github.com/ales-erjavec/orange3.git
    # Branch/ref from which to pull
    BUILD_BRANCH: installer-conda-packages
    # Commit ref/tag to checkout
    BUILD_COMMIT: 'bef87621e84fdc3efbae1044c081a46b1e3110ef'

    # Build the package locally or use the build packages from
    # conda-forge / PyPI. The BUILD_COMMIT must match the package version
    # to build.
    # Comment/override this if building release versions.
    BUILD_LOCAL: 1

    PIP_DISABLE_PIP_VERSION_CHECK: 1
    # disable threaded builds on Python 3.5+ when using numpy's distutils
    # (https://github.com/numpy/numpy/issues/7607)
    BUILD_GLOBAL_OPTIONS: config --with-htmlhelp build -j1

    # build env dependencies for building orange3 wheels or any of its
    # dependencies that do not have wheels available
    BUILD_DEPS: --find-links https://orange.biolab.si/download/files/wheelhouse/ --only-binary numpy wheel==0.29.0 pip~=19.0 numpy~=1.14.0 sphinx==1.8.2

  # Note the python version here refers to the one included in the installer
  # not the one used for building/packaging
  matrix:
    - PYTHON_VERSION: '3.7'
      PLATTAG: win_amd64
      CONDA: C:\Miniconda37-x64\Scripts\conda
      PYTHON: C:\Miniconda37-x64\python
      CONDA_SPEC_FILE:
      # CONDA_SPEC_FILE: ..\specs\win\conda-spec.txt

    - PYTHON_VERSION: 3.6.5
      PLATTAG: win_amd64
      ENVSPEC: ../specs/win/PY36.txt
      PYTHON: C:\Python36-x64

matrix:
  fast_finish: false

cache:
  - '%LOCALAPPDATA%\pip\Cache -> appveyor.yml'

build_script:
  - git clone %REPO%
  - cd orange3
  - git fetch origin %BUILD_BRANCH%
  - git checkout %BUILD_COMMIT%

  - set "PATH_BEFORE_BUILD=%PATH%"
  - set "PATH=C:\msys64\usr\bin;C:\Program Files (x86)\NSIS;%PATH%"

  - >-
    "%PYTHON%" --version
  - >-
    "%PYTHON%" -m pip --version
  - >-
    "%PYTHON%" -m pip list --format=freeze

  - dir C:\Miniconda37-x64\pkgs\
  - dir C:\Miniconda36-x64\pkgs\
  # - dir C:\Miniconda38-x64\pkgs\
  
  - if not "%CONDA%" == "" ( ..\ci\appveyor-conda-build.bat )
  - if "%CONDA%" == "" ( ..\ci\appveyor-build.bat )

  - for %%s in ( dist/Orange3*.exe ) do ( set "INSTALLER=%%s" )
  - echo INSTALLER = %INSTALLER%

  - set "PATH=%PATH_BEFORE_BUILD%"
  - cd ..

test_script:
  # cleanup registry of anaconda reg keys -- this worked for Visual Studio 2015 image
  # - reg delete HKEY_LOCAL_MACHINE\Software\Python\ContinuumAnalytics /f
  # - reg delete HKEY_CURRENT_USER\Software\Python\ContinuumAnalytics /f
  - dir orange3\
  - dir orange3\dist
  # Install in silent mode. Output has to be piped somewhere so the installer
  # runs 'attached' to the console.
  - orange3\dist\%INSTALLER% /S /D=C:\test-install > nul
  # The venv and conda envs create different install layouts.
  - if "%CONDA%" == "" ( set "PYTHON=C:\test-install\Scripts\python" )
  - if not "%CONDA%" == "" ( set "PYTHON=C:\test-install\python" )
  - >-
    "%PYTHON%" --version
  - >-
    "%PYTHON%" -m pip --version
  - >-
    "%PYTHON%" -m pip list --format=freeze
  # Test that orange and all dependencies are installed in a consistent state
  - >-
    "%PYTHON%" -m pip install --no-index --no-cache-dir orange3

  # Run test suite in the installed environment.
  - set ORANGE_DEPRECATIONS_ERROR=1
  - set PYTHONWARNINGS=module
  - >-
    "%PYTHON%" -m unittest -v Orange.tests Orange.widgets.tests
  - mkdir installers
  - move orange3\dist\%INSTALLER% installers\

  # Log the filename and the sha checksum
  - for /f %%s in ( 'sha256sum -b installers/%INSTALLER%' ) do ( set "CHECKSUM=%%s" )
  - echo INSTALLER = %INSTALLER%
  - echo SHA256    = %CHECKSUM%


artifacts:
  - path: installers\*
  - path: conda-pkgs\*
